name: Feature request
description: Suggest an idea for this project
title: '[FEATURE] <title>'
labels: [Feature, Needs Triage]
assignees:
  - jonsugar
body:
- type: markdown
  attributes:
    value: |
      **Is there an existing feature request for this?**
      Please search to see if a feature request already exists for your idea.
- type: checkboxes
  attributes:
    label: Is there an existing feature request for this?
    options:
    - label: I have searched the existing issues
      required: true
